import type { FeatureCollection, Geometry } from 'geojson'

import admin0Url from './admin-0.geojson?url'
import admin1Url from './admin-1.geojson?url'

/**
 * Properties carried by every feature in the bundled Natural Earth layers.
 * Generated by `npm run geo:build` — see scripts/build-geo.mjs.
 */
export interface ZoneProperties {
  /** English display name. */
  name: string
  /**
   * ISO 3166-1 alpha-2 code, matching a location's `country_code`. Absent for
   * the handful of territories Natural Earth leaves without an ISO code.
   */
  country_code?: string
  /**
   * ISO 3166-2 subdivision code, e.g. `US-CA`. Admin-1 only, and absent for
   * subdivisions that have no ISO code of their own.
   */
  code?: string
}

export type ZoneCollection = FeatureCollection<Geometry, ZoneProperties>

async function fetchZones(url: string): Promise<ZoneCollection> {
  const response = await fetch(url)
  if (!response.ok) {
    throw new Error(`Failed to load zone geometry (${response.status})`)
  }
  return (await response.json()) as ZoneCollection
}

/**
 * The layers are megabytes of geometry, so they are emitted as standalone
 * assets and fetched on first use rather than bundled into the entry chunk.
 * The result is memoised; a failed load is not, so a retry can succeed.
 */
function lazyLayer(url: string): () => Promise<ZoneCollection> {
  let pending: Promise<ZoneCollection> | undefined

  return () => {
    pending ??= fetchZones(url).catch((error: unknown) => {
      pending = undefined
      throw error
    })
    return pending
  }
}

/** Countries (Natural Earth admin-0, 1:50m). */
export const loadCountryZones = lazyLayer(admin0Url)

/** States and provinces (Natural Earth admin-1, 1:10m). */
export const loadSubdivisionZones = lazyLayer(admin1Url)
